Tickets/src/Tickets/Controllers/BaseLocalizationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Tickets.Controllers
{
    public class BaseLocalizationController : Controller
    {
        public ActionResult ChooseLanguage(string culture)
        {
            if (culture.Equals("en"))
            {
                HttpContext.Session.SetString("culture", "en");
            }
            if (culture.Equals("ru"))
            {
                HttpContext.Session.SetString("culture", "ru");
            }
            if (culture.Equals("be"))
            {
                HttpContext.Session.SetString("culture", "be");
            }
            return Redirect("~/Events/Events?culture=" + HttpContext.Session.GetString("culture"));
        }
    }
}

Tickets/src/Tickets/Controllers/UserManagerRoleController.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Tickets.Business.Abstract;
using Tickets.Data.Models;
using Tickets.Models;


namespace Tickets.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserManagerRoleController : Controller
    {
        public IUserService UserService { get; set; }
        public IStringLocalizer<BaseLocalizationController> StringLocalizer { get; set; }

        public UserManagerRoleController(IUserService userService, IStringLocalizer<BaseLocalizationController> stringLocalizer)
        {
            UserService = userService;
            StringLocalizer = stringLocalizer;
        }

        [HttpGet]
        
        public ActionResult UsersInRole()
        {
            return View("UserInRole",new UserInRoleModel { ListUserAccount = UserService.GetAllUserAccounts()});
        }

        public ActionResult ChangeRole(int id)
        {
            return View("ChangeRoleForuser",new UserInRoleModel {  UserAccount = UserService.GetUserAccountByid(id)});
        }

        [HttpPost]
        public ActionResult ChangeRolePost(UserInRoleModel userAccount)
        {
            try
            {
                UserService.ChangeRoleByUser(userAccount.NewRole, userAccount.Id);
                return RedirectToAction("UsersInRole");
            }
            catch (ValidationException e)
            {
                ModelState.AddModelError("", StringLocalizer[e.Message]);
                return View("ChangeRoleForuser", userAccount);
            }
        }
    }
}

Tickets/src/Tickets/Views/Share/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="~/CSS/site.css" />
</head>

<body>
<div class="wrapper">
    <ul class="navbar">
        <li class="navbar-left">
            <a asp-controller="Events" asp-action="Events" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["Events"]</a>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            <li class="navbar-right">
                <a>@Localizer["Hello"] @User.Identity.Name</a>
                <a asp-controller="Login" asp-action="LoginOut" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["Sign out"]</a>
            </li>
            <li class="navbar-right">
                @if (User.IsInRole("admin"))
                {
                    <a asp-controller="UserManagerRole" asp-action="UsersInRole" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["Users manager"]</a>
                    <a asp-controller="EventManager" asp-action="GetAllEvent" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["Event manager"]</a>
                }
                <a asp-controller="UserTickets" asp-action="UserTickets" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["My tickets"]</a>
                <a asp-controller="UserOrders" asp-action="UserOrders" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["My orders"]</a>
                <a asp-controller="UserInfo" asp-action="UserInfo" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["Profile"]</a>
            </li>
        }
        else
        {
            <li class="navbar-right">
                <a asp-controller="Login" asp-action="Registration" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["Sign up"]</a>
            </li>
            <li class="navbar-right">
                <a asp-controller="Login" asp-action="Login" asp-route-culture="@Url.ActionContext.HttpContext.Session.GetString("culture")">@Localizer["Sign in"]</a>
            </li>
        }
    </ul>
</div>
<div class="content">
    @RenderBody()
</div>
<div class="footer">
    <div class="link-choose-language">
        <a class="lang-en" asp-controller="BaseLocalization" asp-action="ChooseLanguage" asp-route-culture="en">EN</a>
        <a class="lang-ru" asp-controller="BaseLocalization" asp-action="ChooseLanguage" asp-route-culture="ru">RU</a>
        <a class="lang-be" asp-controller="BaseLocalization" asp-action="ChooseLanguage" asp-route-culture="be">BY</a>
    </div>
</div>
</body>
</html>