Tickets/src/Tickets/Controllers/EventManager/CityController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Localization;
using Tickets.Business.Abstract;
using Tickets.Models;

namespace Tickets.Controllers.EventManager
{
    [Authorize(Roles = "admin")]
    public class CityController : Controller
    {
        private readonly ICityService _cityService;
        private readonly IStringLocalizer<BaseLocalizationController> _stringLocalizer;

        public CityController(ICityService cityService, IStringLocalizer<BaseLocalizationController> stringLocalizer)
        {
            _cityService = cityService;
            _stringLocalizer = stringLocalizer;
        }
        public ActionResult City()
        {
            return View("../EventManager/CreateCity");
        }

        [HttpPost]
        public ActionResult AddCity(CityModel city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _cityService.AddCity(city.Name);
                    return
                        RedirectToRoute(
                            new
                            {
                                controller = "Venue",
                                action = "Venue",
                                culture = HttpContext.Session.GetString("culture")
                            });
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", _stringLocalizer[e.Message]);
                    return View("CreateCity", city.Name);
                }
            }
            ModelState.AddModelError("","Enter your name uncorect");
            return View("CreateCity", city.Name);
        }
    }
}

Tickets/src/Tickets/Controllers/EventManager/EventManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tickets.Business.Abstract;
using Tickets.Data.Models;
using Tickets.Models;

namespace Tickets.Controllers.EventManager
{
    [Authorize(Roles = "admin")]
    public class EventManagerController : Controller
    {
        private IEventsService _eventService;
        private IVenueService _venueService;
        private ICityService _cityService;
        private IImageService _imageService;

        public EventManagerController(IEventsService eventsService, IVenueService venueService,
            ICityService cityService, IImageService imageService)
        {
            _eventService = eventsService;
            _venueService = venueService;
            _cityService = cityService;
            _imageService = imageService;
        }

        [Authorize(Roles = "admin")]
        public ActionResult GetAllEvent()
        {
            return View("EventManager", new EventModel {ListEvents = _eventService.GetAllEvents()});
        }

        [Authorize(Roles = "admin")]
        public ActionResult EditEvent(int id)
        {
            return View("CreateOrUpdateEvent", new EventModel
            {
                Event = _eventService.GetEventById(id),
                ListCity = _cityService.GetAllCity(),
                ListVenue = _venueService.GetAllVenue()
            });
        }


        public ActionResult EditEventPost(EventModel eventModel)
        {
            if (ModelState.IsValid)
            {
                Event ev = _eventService.GetEventByName(eventModel.Name);
                ev.Name = eventModel.Name;
                ev.Date = eventModel.Date;
                if (eventModel.Image != null)
                {
                    ev.PathBanner =
                        _imageService.GetImageUri(_imageService.SaveImage(eventModel.Image.FileName,
                            eventModel.Image.OpenReadStream()));
                }
                ev.Description = eventModel.Description;
                ev.VenueId = _venueService.GetVenueByName(eventModel.VenueName).Id;
                _eventService.UpdateEvent(ev);
                return RedirectToAction("GetAllEvent");
            }
            return View("CreateOrUpdateEvent", eventModel);
        }

        public ActionResult RemoveEvent(int id)
        {
            if (ModelState.IsValid)
            {
                _eventService.RemoveEvent(id);
                return RedirectToAction("GetAllEvent");
            }
            ModelState.AddModelError("", "Choose value not correct");
            return LocalRedirect("");
        }

        [HttpGet]
        public ActionResult CreateEvent()
        {
            return View("CreateOrUpdateEvent", new EventModel
            {
                ListCity = _cityService.GetAllCity(),
                ListVenue = _venueService.GetAllVenue()
            });
        }

        [HttpPost]
        public ActionResult CreateEvent(EventModel eventModel)
        {
            if (ModelState.IsValid)
            {
                _eventService.AddEvent(new Event
                {
                    Name = eventModel.Name,
                    Date = eventModel.Date,
                    PathBanner =
                        _imageService.GetImageUri(_imageService.SaveImage(eventModel.Image.FileName,
                            eventModel.Image.OpenReadStream())),
                    Description = eventModel.Description,
                    VenueId = _venueService.GetVenueByName(eventModel.VenueName).Id
                });
                return RedirectToAction("GetAllEvent");
            }
            return View("CreateOrUpdateEvent", eventModel);
        }
    }
}

Tickets/src/Tickets/Controllers/EventManager/VenueController.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Tickets.Business.Abstract;
using Tickets.Data.Models;
using Tickets.Models;

namespace Tickets.Controllers.EventManager
{
    [Authorize(Roles = "admin")]
    public class VenueController : Controller
    {
        private readonly IVenueService _venueService;
        private readonly ICityService _cityService;
        private readonly IStringLocalizer<BaseLocalizationController> _stringLocalizer;

        public VenueController(IVenueService venueService, ICityService cityService,
            IStringLocalizer<BaseLocalizationController> stringLocalizer)
        {
            _venueService = venueService;
            _cityService = cityService;
            _stringLocalizer = stringLocalizer;
        }
        
        public ActionResult Venue()
        {
            return View("../EventManager/CreateVenue", new VenueModel {ListCity = _cityService.GetAllCity()});
        }

        [HttpPost]
        public ActionResult AddVenue(VenueModel venue)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _venueService.AddVenue(new Venue
                    {
                        Name = venue.Name,
                        Adress = venue.Adress,
                        CityId = _cityService.GetCityByName(venue.NameCity).Id
                    });

                    return
                        RedirectToRoute(
                            new
                            {
                                controller = "EventManager",
                                action = "GetAllEvent",
                                culture = HttpContext.Session.GetString("culture")
                            });
                }
                catch (ValidationException e)
                {
                    ModelState.AddModelError("", _stringLocalizer[e.Message]);
                    return View("CreateVenue", venue);
                }
            }
            ModelState.AddModelError("", "Enter your data uncorect");
            return View("CreateVenue", venue);
        }
    }
}

Tickets/src/Tickets/Views/EventManager/CreateCity.cshtml
@model CityModel

<form asp-controller="City" asp-action="AddCity" Method="post">
    <div class="userinfo-box">
        <div class="userinfo-field">
            @Localizer["Name city"]:
        </div>
        <div class="userinfo-value">
            <input type="text" asp-for="Name" />
        </div>
    </div>
    <input type="submit" class="buttonAuth" Value=@Localizer["Add city"] />
</form>

Tickets/src/Tickets/Views/EventManager/CreateOrUpdateEvent.cshtml
@model EventModel

<div>
    @if (Model.Event == null)
    {
        <form asp-controller="EventManager" asp-action="CreateEvent" enctype="multipart/form-data" Method="post">
            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Event"]:
                </div>
                <div class="userinfo-value">
                    <input type="text" asp-for="Name" Value="" />
                </div>
            </div>
            
            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Event date"]:
                </div>
                <div class="userinfo-value">
                    <input type="datetime" asp-for="Date" Value="" />
                </div>
            </div>
            
            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Name venue"]:
                </div>
                <div class="userinfo-value">
                    <select asp-for="VenueName">
                        @foreach (Venue venue in Model.ListVenue)
                        {
                            <option>@venue.Name</option>
                        }
                    </select>
                    <a asp-controller="Venue" asp-action="Venue">@Localizer["Add new venue"]</a>
                </div>
            </div>
            
            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Path image"]:
                </div>
                <div class="userinfo-value">
                    <input type="file" asp-for="Image" class="form-control" />
                </div>
            </div>
            
            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Event description"]:
                </div>
                <div class="userinfo-value">
                    <input type="text" asp-for="Description" Value="" />
                </div>
            </div>
            <div>
                <input type="submit" class="buttonAuth" Value=@Localizer["Create"] />
            </div>
        </form>
    }
    else
    {
        <form asp-controller="EventManager" asp-action="EditEventPost" enctype="multipart/form-data" Method="post">
            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Event"]:
                </div>
                <div class="userinfo-value">
                    <input type="text" asp-for="Name" Value="@Model.Event.Name" />
                </div>
            </div>

            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Event date"]:
                </div>
                <div class="userinfo-value">
                    <input type="datetime" asp-for="Date" Value="@Model.Event.Date" />
                </div>
            </div>

            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Name venue"]:
                </div>
                <div class="userinfo-value">
                    <select asp-for="VenueName">
                        @foreach (Venue venue in Model.ListVenue)
                        {
                            <option>@venue.Name</option>
                        }
                    </select>
                    <a asp-controller="Venue" asp-action="Venue">@Localizer["Add new venue"]</a>
                </div>
            </div>

            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Path image"]:
                </div>
                <div class="userinfo-value">
                    <input type="file" asp-for="Image" class="form-control" />
                </div>
            </div>

            <div class="userinfo-box">
                <div class="userinfo-field">
                    @Localizer["Event description"]:
                </div>
                <div class="userinfo-value">
                    <input type="text" asp-for="Description" Value="@Model.Event.Description" />
                </div>
            </div>
            <div>
                <input type="submit" class="buttonAuth" Value=@Localizer["Edit"] />
            </div>
        </form>
    }
</div>

Tickets/src/Tickets/Views/EventManager/CreateVenue.cshtml
@model VenueModel
<div>
    <form asp-controller="Venue" asp-action="AddVenue" Method="post">
        <div class="userinfo-box">
            <div class="userinfo-field">
                @Localizer["Venue name"]:
            </div>
            <div class="userinfo-value">
                <input type="text" asp-for="Name" />
            </div>
        </div>
        <div class="userinfo-box">
            <div class="userinfo-field">
                @Localizer["Adress venue"]:
            </div>
            <div class="userinfo-value">
                <input type="text" asp-for="Adress" />
            </div>
        </div>
        <div class="userinfo-box">
            <div class="userinfo-field">
                @Localizer["City"]:
            </div>
            <div class="userinfo-value">
                <select asp-for="@Model.NameCity">
                    @foreach (City city in Model.ListCity)
                    {
                        <option>@city.Name</option>
                    }
                </select>
                <a asp-controller="City" asp-action="City">@Localizer["Add new city"]</a>
            </div>
        </div>
        <div>
            <input type="submit" class="buttonAuth" Value=@Localizer["Add venue"] />
        </div>
    </form>
</div>

Tickets/src/Tickets/Views/EventManager/EventManager.cshtml
@model EventModel

<table>
    <tr>
        <td>
            @Localizer["Event"]
        </td>
        <td>
            @Localizer["Event date"]
        </td>
        <td>
            @Localizer["City"]
        </td>
        <td>
            @Localizer["Adress venue"]
        </td>
        <td>
            @Localizer["Name venue"]
        </td>
        <td>
            @Localizer["Image"]
        </td>
        <td>
            @Localizer["Event description"]
        </td>
    </tr>
    @foreach (Event ev in Model.ListEvents)
    {
        <tr>
            <td>
                @ev.Name
            </td>
            <td>
                @ev.Date
            </td>
            <td>
                @ev.Venue.City.Name
            </td>
            <td>
                @ev.Venue.Adress
            </td>
            <td>
                @ev.Venue.Name
            </td>
            <td>
                <div class="event-manager-row-image">
                    <img class="event-image" src="@Url.Content(ev.PathBanner)" />
                </div>
            </td>
            <td>
                @ev.Description
            </td>
            <td>
                <a asp-controller="EventManager" asp-action="EditEvent" asp-route-id="@ev.Id"> @Localizer["Edit"] </a>
                <a asp-controller="EventManager" asp-action="RemoveEvent" asp-route-id="@ev.Id"> @Localizer["Remove"] </a>
            </td>
        </tr>
    }
</table>
<a asp-controller="EventManager" asp-action="CreateEvent"><button class="buttonAuth">@Localizer["Create new event"]</button></a>